default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  user: <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>

development:
  <<: *default
  database: alvt_development

test:
  <<: *default
  database: alvt_test

production:
  <<: *default
  database: alvt_production
  username: alvt
  password: <%= ENV["ALVT_DATABASE_PASSWORD"] %>
