require: rubocop-rails

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - spec/**/*
    - config/routes.rb
    - config/environments/**/*
    - lib/tasks/**/*

Layout/LineLength:
  Max: 120

Metrics/ClassLength:
  Max: 160

AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable
  Exclude:
    - 'Gemfile.lock'
    - 'bin/**/*'
    - 'bin/'
    - 'db/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'log/**/*'
    - 'db/schema.rb'
    - 'config/initializers/**/*'
